.Dd October 6, 2018
.Dt PERP_INTRO 8
.Os
.Sh NAME
.Nm perp_intro
.Nd introduction to the perp service management framework
.Sh SYNOPSIS
.Ar /etc/perp
.Sh DESCRIPTION
.Ss Purpose
The
.Ar perp
service management framework provides a set of daemons and utilities to
start, monitor, log, and control a collection of persistent processes.
This document provides a basic overview of the system.
Further details may be found in the manual pages as referenced.
.Ss Terms
.Bl -tag -width Ds
.It Dq persistent process
Any long-running program,
normally intended to start at system boot
and continue running until system shutdown.
Also known and often described as a ``service''.
A persistent process will normally provide some essential system service
on-demand.
Programs that service email, domain name queries, and http requests
are examples of services that are normally run as persistent processes.
.It Dq service definition
A service definition is
the set of
.Xr perpetrate 5
runscripts and associated files that tell the
.Xr perpd 8
program how to start, run, and optionally log a service.
The base directory for a collection of service definitions is normally
.Pa /etc/perp .
The service definition for a particular service
.Dq foo
will then be installed in the service definition directory
.Pa /etc/perp/foo .
.It Dq service activation
A service definition may be installed and configured as summarized above,
but does not become operative until it is specifically activated.
An activated service is then recognized by the
.Xr perpd 8
scanner.
Service activation is controlled by setting the
.Xr sticky 7
bit on the service definition directory.
Setting the sticky bit activates the service,
unsetting the sticky bit deactivates the service.
The sticky bit is manipulated on the command line with the
.Xr chmod 1
utility,
or with the
.Ar A
and
.Ar B
commands to the
.Xr perpctl 8
utility.
.It Dq process supervisor
Some program, itself a persistent process,
that starts and monitors another program to ensure its persistency.
.El
.Ss Daemon Programs
.Bl -tag -width Ds
.It Xr perpd 8
the principal daemon of a perp installation:
service directory scanner, process supervisor, and service controller;
normally operating on the service installation directory
.Pa /etc/perp
.It Xr perpboot 8
recommended utility for starting
.Xr perpd 8
.El
.Ss Control Programs
.Bl -tag -width Ds
.It Xr perp-setup 8
one-time post-installation configurator for initializing a
.Ar perp
system
.It Xr perpctl 8
administrative utility for runtime control of
.Xr perpd 8
.It Xr perphup 8
rescan trigger utility for
.Xr perpd 8
.El
.Ss Query Programs
.Bl -tag -width Ds
.It Xr perpls 8
perp service lister
.It Xr perpstat 8
perp status reporter
.It Xr perpok 8
perp service checker
.El
.Ss Logging Programs
.Bl -tag -width Ds
.It Xr sissylog 8
log stdin to
.Xr syslog 3
.It Xr tinylog 8
log stdin to directory of rotated logfiles
.El
.Sh FILES
The service installation directory
.Pa /etc/perp
will have the following layout:
.Pp
.Bl -tag -width /etc/perp/foo/rc.main -compact
.It Pa /etc/perp
base directory for service installation, monitored by
.Xr perpd 8
.It Pa /etc/perp/.boot
configuration directory used by
.Xr perpboot 8
to start
.Xr perpd 8
.It Pa /etc/perp/.control
runtime control directory for the
.Pa /etc/perp
installation directory;
normally a symlink to
.Pa /var/run/perp
.It Pa /etc/perp/foo
.Xr perpetrate 5
definition directory for some service
.Dq foo
under supervision of
.Xr perpd 8
.It Pa /etc/perp/foo/rc.log
.Xr perpetrate 5
optional runscript for starting/resetting a logger for service
.Dq foo
.It Pa /etc/perp/foo/rc.main
.Xr perpetrate 5
required runscript for starting/resetting the service
.Dq foo
.El
.Sh SEE ALSO
.Xr perp-setup 8 ,
.Xr perpboot 8 ,
.Xr perpctl 8 ,
.Xr perpd 8 ,
.Xr perpetrate 5 ,
.Xr perphup 8 ,
.Xr perpls 8 ,
.Xr perpok 8 ,
.Xr perpstat 8 ,
.Xr sissylog 8 ,
.Xr tinylog 8
.Sh AUTHORS
.An Wayne Marshall
